# ==============================================================
# CONFIGURACIÓN DE PRODUCCIÓN (Variables de Entorno)
# ==============================================================

spring.application.name=RadioAcademy

# FRONTEND: En local usa localhost, en prod leerá la variable
app.frontend.url=${FRONTEND_URL:http://localhost:4200}

# BASE DE DATOS
# En prod, la nube inyecta la URL completa automáticamente
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
# En producción 'validate' es más seguro para no romper datos por error
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# SEGURIDAD JWT
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXPIRATION:86400000}

# SUBIDA DE ARCHIVOS
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# API KEYS EXTERNAS
resend.api.key=${RESEND_API_KEY}
stripe.currency=eur
stripe.api.key=${STRIPE_SECRET_KEY}

# WEBHOOKS DE STRIPE
stripe.success.url=${app.frontend.url}/payment/success
stripe.cancel.url=${app.frontend.url}/payment/cancel

# DATA SEEDING (Admin inicial)
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}